### ISSUE TITLE
We need a better way back to the home screen

### ISSUE THREAD

**Issue by moskovich** [apc-io/apc-firefox-os#10]
Current we use the home key. This is not-obvious.

**Comment by ferndot** [comment]
What is the better way?

**Comment by trungnt** [comment]
This is, for now, changed to "Meta" for normal PC keyboards and "Command" for Mac keyboards!

**Comment by lechau-apc** [comment]
And also a Home icon is added to the notification bar, so you can go home when a hardware keyboard is not available but a mouse :)
