### ISSUE TITLE
config.sh Error

### ISSUE THREAD

**Issue by cgaspard** [apc-io/apc-firefox-os#33]
When I'm running the config.sh script, I started getting this error this morning.   Haven't had this error until today.

object 12fd10c20115046dcd2fbe468a45e566f38ffbc9
type commit
tag v1.12.7
tagger Conley Owens cco3@android.com 1381959964 -0700

repo 1.12.7

gpg: Signature made Wed 16 Oct 2013 04:46:04 PM CDT using RSA key ID 692B382C
gpg: Can't check signature: public key not found
error: could not verify the tag 'v1.12.7'

**Comment by trungnt** [comment]
Hi @cgaspard, could you please provide us more information about that? e.g: what is the exact command you used, any other messages beside above, etc.

Could you please try to update B2G repo?

FYI, we migrated to Mozilla newest update, still under testing, but you can switch to the branch apc8950-master of B2G repo and do the update.

**Comment by metta2085** [comment]
Hi,
I found that repo project has a problem with recent release. To fix this, remove folder "~/.repoconfig" and then replace with latest repo: 
"curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > YourProjectFolder/repo"
Detail is at here: http://www.marshut.com/wrrts/repo-release-1-12-4.html.

**Comment by cgaspard** [comment]
Thanks guys.   I found the same solution.  Updating repo fixed the problem for me.
