### ISSUE TITLE
Could not download source from github

### ISSUE THREAD

**Issue by masap** [apc-io/apc-firefox-os#37]
I tried to build along with https://github.com/apc-io/apc-firefox-os/blob/master/building-guide.md.

However I got an error after typing this command.
## $ git clone git@github.com:apc-io/apc_b2g_b2g.git B2G

Cloning into 'B2G'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
## and the repository exists.

After that, I tried this command. It works.
$ git clone git://github.com/apc-io/apc_b2g_b2g.git B2G

But this command fails.
## $ ./config.sh wmid

Get git@github.com:apc-io/apc_8950_manifests.git
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by trungnt** [comment]
Hi @masap, 
I think the problem is because of lacking ssh key in your GitHub account. Did you setup it yet? If not, please follow the guide here: https://help.github.com/articles/generating-ssh-keys !

**Comment by masap** [comment]
Thanks ! It works !

**Comment by trungnt** [comment]
Great! Added a note about this to the building guide :)
