### ISSUE TITLE
How to enable latest Gaia ?

### ISSUE THREAD

**Issue by masap** [apc-io/apc-firefox-os#38]
I found a Change log on https://github.com/apc-io/apc-firefox-os/blob/master/README.md.

It says "Updated to the new Mozilla code from 2013.12.25 (gecko & gaia).".

I rebuild firefox os along with "BUILDING STEPS".
But version number in "Settings" application of Firefox OS displays 1.1.0.
I expects 1.4.0.

How to enable latest Gaia ?

**Comment by trungnt** [comment]
Hi @masap,
Sorry for the late reply. We were on the new year holidays.
So FYI, we were using a difference branches of Gaia & Gecko (not the master one) before. And the B2G branch for that is **apc8950**. Later, we switched to Mozilla master branches from release repo. And we used a new B2G branch for that: **apc8950-master**.
Could you please check if you are using the **apc8950-master** branch for B2G repository?

**Comment by masap** [comment]
@trungnt Thanks for your reply.
Yes I'm using apc8950-master branch.

**Comment by trungnt** [comment]
@masap: I did a clean build and we still have version 1.4.0.0-prerelease here. Let's make some comparison about git revisions.
- B2G: 05ac81614109b
- gecko: c403951d780
- gaia: 804fb4077ff
- gonk-mics: 49c722fa1a5e

**Comment by masap** [comment]
@trungnt 
I did

$ cd B2G/
$ git pull
$ ./repo sync

and checked revisions. gecko's git revision is different from yours.

B2G: 05ac81614109b7d8d3ce7088cdd5610dd2b63742
gecko: 9f65e7ce52f7ecf33b7b8c7958cfb6f275307a8e
gaia: 804fb4077ff2e592098d8ab86264bd16ffa1855c
gonk-misc: 49c722fa1a5e1873fa0010829fd97d0b74009ca5

Is there any wrong on my steps ?

My steps are below. 

$ git clone git@github.com:apc-io/apc_b2g_b2g.git B2G
$ cd B2G
$ git checkout apc8950-master
$ ./config.sh wmid
$ vi .userconfig
export CC=gcc-4.6
export CXX=g++-4.6
$ ./build.sh -j8

**Comment by trungnt** [comment]
@masap 
Ok, I checked.
There's a difference in gecko because I had a new commit there, but that is not the problem.
I checked in the code and the OS version is defined in gecko/b2g/confvar.sh, you can see it here: https://github.com/apc-io/apc_b2g_gecko/blob/9f65e7c/b2g/confvars.sh. 
<code>
MOZ_B2G_VERSION=1.4.0.0-prerelease
</code>

I changed that value and rebuild gecko to test. It just work fine. So I have no idea why you still have version 1.1.0.

**Comment by masap** [comment]
@trungnt
I tried to clean build.
confvars.sh has MOZ_B2G_VERSION=1.4.0.0-prerelease.
But still built image is 1.1.0...

**Comment by trungnt** [comment]
@masap
This is strange, may be you can ask Mozilla about this problem :)
